# The Library: Forbidden Section

PREFIX: ">"

LOGGING:
  MESSAGE_LOGS:
    CHANNEL: saber-mod-log
  MOD_LOGS:
    CHANNEL: saber-mod-log
  XP_LOGS:
    CHANNEL: saber-xp-log

WELCOMER:
  ENABLED: true
  CHANNEL: 614409461393653760
  MESSAGE_LIVES: 15

ROLE_REWARDS:
  ROLE_1:
    SHOP_ID: 1 # Номер в магазине
    PRICE: 1400 # Стоимость
    ROLE: 614705075973259275 # ID роли
  ROLE_2:
    SHOP_ID: 2
    PRICE: 2750
    ROLE: 614705105543102474
  ROLE_3:
    SHOP_ID: 3
    PRICE: 4500
    ROLE: 614705127126859786
  ROLE_4:
    SHOP_ID: 4
    PRICE: 6500
    ROLE: 614705150120165377
  ROLE_5:
    SHOP_ID: 5
    PRICE: 8700
    ROLE: 614705165219659787
  ROLE_6:
    SHOP_ID: 6
    PRICE: 11700
    ROLE: 614705182307123227
