# The Library

WELCOMER:
  ENABLED: true
  CHANNEL: 612406451863945257
  MESSAGE_LIVES: 20

ROLE_REWARDS:
  ROLE_1:
    SHOP_ID: 1 # Номер в магазине
    PRICE: 1400 # Стоимость
    ROLE: 612416961460174860 # ID роли
  ROLE_2:
    SHOP_ID: 2
    PRICE: 2750
    ROLE: 612416409406013464
  ROLE_3:
    SHOP_ID: 3
    PRICE: 4500
    ROLE: 612417124618731520
  ROLE_4:
    SHOP_ID: 4
    PRICE: 6500
    ROLE: 612418224734208000
  ROLE_5:
    SHOP_ID: 5
    PRICE: 8700
    ROLE: 612417388238995466
  ROLE_6:
    SHOP_ID: 6
    PRICE: 11700
    ROLE: 612417528664293382